name: Presubmit test
run-name: ${{ github.actor }} is running presubmit tests
on: [push]
jobs:
  testPython:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is running on ${{ runner.os }} server hosted by GitHub"
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Python   
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: python -m pip install --upgrade -r scrabble-detection/requirements.txt
        # TODO: Cache the model instead
      - name: Train the model
        run: python scrabble-detection/train.py
      - name: Test Python classes using the model
        run: pytest scrabble-detection/test_board.py
      - name: Compare the test results to the main branch tests (placeholder)
        run: |
          git checkout HEAD~1 && git status
  testJava:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is running on ${{ runner.os }} server hosted by GitHub"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test Java classes
        run: ./gradlew test
